version: 2.1
#orbs:
#  python: circleci/python@2
jobs:
  build:
    docker:
      - image: cimg/base:stable
    working_directory: ~/project
    steps:
      - checkout:
          path: ~/project
      - run:
          name: Build
          command: bash ./resources/build_libmicrohttpd.sh --compile && make CFLAGS="-I/tmp/libmicrohttpd_install/include" LDFLAGS="-L/tmp/libmicrohttpd_install/lib"
      - store_test_results:
          path: buildlog.txt
  deploy:
    docker:
      - image: cimg/base:stable
    steps:
      # Replace this with steps to deploy to users
      - run:
          name: deploy
          command: '#e.g. ./deploy.sh'
workflows:
  build-and-test:
    jobs:
      - build
    # - deploy:
    #     requires:
    #       - test-python
